services:
  webserver:
    container_name: itdp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_CONNECTION=mysql
      - DB_HOST=db_server
      - DB_DATABASE=portfolio_db
      - DB_USERNAME=portfolio_user
      - DB_PASSWORD=portfolio_password
    depends_on:
      - db_server
    networks:
      - portfolio-network

  db_server:
    image: mysql:8.0
    container_name: showcase_database
    restart: always
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql_data: