services:
  - type: web
    name: itdp-portfolio-web
    env: docker
    repo: https://github.com/HZ-ICT1-2526/itdp-ratkooo
    plan: free
    region: frankfurt
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/public
      - key: DB_CONNECTION
        value: mysql

      # Maps Aiven MySQL integration parameters into your PHP variables
      - key: DB_HOST
        fromDatabase:
          name: portfolio-mysql-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-mysql-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-mysql-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-mysql-db
          property: password

databases:
  - name: portfolio-mysql-db
    databaseEngine: mysql     # <--- FORCES RENDER TO PROVISION A MYSQL INSTANCE
    plan: free
    region: frankfurt