services:
  # 1. Your Custom PHP Web Application
  - type: web
    name: itdp-portfolio-web
    env: docker
    repo: https://github.com/HZ-ICT1-2526/itdp-ratkooo
    plan: free
    region: frankfurt
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/public
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: showcase-database
      - key: DB_DATABASE
        value: portfolio_db
      - key: DB_USERNAME
        value: portfolio_user
      - key: DB_PASSWORD
        value: portfolio_password

  # 2. Your Dedicated MySQL Container (Private Cloud Instance)
  - type: pserv
    name: showcase-database
    env: docker
    repo: https://github.com/render-examples/mysql
    plan: free
    region: frankfurt
    envVars:
      - key: MYSQL_DATABASE
        value: portfolio_db
      - key: MYSQL_USER
        value: portfolio_user
      - key: MYSQL_PASSWORD
        value: portfolio_password
      - key: MYSQL_ROOT_PASSWORD
        value: root_password
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1